services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/traefik_config/traefik_dynamic_config.toml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=julio.cruz@dicode.com.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--log.level=DEBUG"  # Modo debug para diagnóstico
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic_config.toml:/traefik_config/traefik_dynamic_config.toml:ro"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true

