# Configuração dinâmica do Traefik

[http]
  [http.routers]
    [http.routers.financeiro]
      rule = "Host(`prosperai.site`)"
      service = "financeiro"
      entrypoints = ["websecure"]
      [http.routers.financeiro.tls]
        certResolver = "myresolver"
    
    [http.routers.financeiro-http]
      rule = "Host(`prosperai.site`)"
      service = "financeiro"
      entrypoints = ["web"]

  [http.services]
    [http.services.financeiro]
      [http.services.financeiro.loadBalancer]
        [[http.services.financeiro.loadBalancer.servers]]
          url = "http://controle_financeiro_app:5005/"
        passHostHeader = true
